AbstractAttributedCharacterIteratorAttributeConverter (and therefore TextAttributeConverter) will check first if it can access the possible constants of the type by reflection. NoClassDefFoundError raised in GAE accessing the fields of restricted types by reflection will be handled.
git-svn-id: http://svn.codehaus.org/xstream/trunk@2163 9830eeb5-ddf4-0310-9ef7-f4b9a3e3227e